### ISSUE TITLE
Looking for exe's on install

### ISSUE THREAD

**Issue by Lokdei** [MrC0rrupted/WinLaunch#10]
Hi

Windows developers add some program shortcuts to the location:
C:\ProgramData\Microsoft\Windows\Start Menu\Programs 

I wish that on WinLaunch install (or by going to the settings) we could look for these programs and have it automatically, once, search for these shortcuts and add them to the WinLaunch screen. 

Would you accept a PR if I include this functionality?

**Comment by MrC0rrupted** [comment]
sure, ill accept it

**Comment by MrC0rrupted** [comment]
Added in 0.5.7.0
