### ISSUE TITLE
Checking for updates

### ISSUE THREAD

**Issue by FoxyDrew** [MrC0rrupted/WinLaunch#17]
I absolutely love that your updating this app every day or multiple times a day - however I just use it as a glorified game launcher and havent had an issue in years.

Can we please get the option to disable update checks? Also...whats checking for updates? I blocked winlaunch.exe in firewall for both inbound and outbound but its still seeing a new update somehow

**Comment by ohabu** [comment]
v.0.6.7.1 fixed this issue.

**Comment by FoxyDrew** [comment]
> v.0.6.7.1 fixed this issue.

Allowing me to "lower" the frequency of updates is not the same as being able to disable them
