### ISSUE TITLE
Sort by Name

### ISSUE THREAD

**Issue by azhe403** [MrC0rrupted/WinLaunch#18]
When adding an app to Launcher, the app is not sorted because added items are always on end.

Is it possible to add the option to sort items by Name?

**Comment by MrC0rrupted** [comment]
added in 0.6.8.0

**Comment by azhe403** [comment]
Is it possible to add an option to Folder-first for sort by name? sorry

![image](https://user-images.githubusercontent.com/17938038/198883621-1a023f3d-7c5d-44aa-a722-fa0c799058f7.png)

**Comment by MrC0rrupted** [comment]
added in 0.6.8.2
