### ISSUE TITLE
Request: Checking for updates at a certain time periods

### ISSUE THREAD

**Issue by fzhukov** [MrC0rrupted/WinLaunch#24]
Problem: I like to keep my apps up to date, but in this case is decently annoying the pop-up window with the offer to update the application, especially on last week, it intercepts the focus when I'm working or playing. In competitive online games, this is a problem.

Solution: If it's not difficult for you, please add the ability to check for updates at certain time periods.

Thanks in advance. :)

**Comment by MrC0rrupted** [comment]
Sorry about that, you can already disable frequent update checks in the settings under "about"
when unchecked WinLaunch only checks for updates at the start

**Comment by fzhukov** [comment]
Oh, thanks, don't know about that. I think it will suit me.
