### ISSUE TITLE
Crash on Windows 11

### ISSUE THREAD

**Issue by philipjholm** [MrC0rrupted/WinLaunch#3]
I have a weird bug on Windows 11. When doing a win+tab and the setting "pin WinLaunch to the desktop" is checked the whole program crashes.

**Comment by azhe403** [comment]
In my PC just enable pin WinLaunch to the desktop, and WinLaunch hang after it restart

![image](https://user-images.githubusercontent.com/17938038/198275597-16aa535a-f2fb-42ff-833e-dbb745483242.png)

**Comment by MrC0rrupted** [comment]
Hey, the pin to desktop feature is very buggy, I recommend against using it
at the moment, I will try to work on it in the coming weeks though

Kind regards
C0rrupted

**Comment by MrC0rrupted** [comment]
pin to desktop beta is back in 0.6.7.0
