### ISSUE TITLE
Allow flipping pages via touchpad gestures

### ISSUE THREAD

**Issue by dyanishev** [MrC0rrupted/WinLaunch#30]
Please consider letting to flip pages via touchpad scrolling gesture.
Right now I'm only able to flip pages by tapping one finger on an empty space on springboard and then dragging left or right.
It would be much more convenient if you could use two finger gesture used on laptops for scrolling

**Comment by dyanishev** [comment]
P.S. To clarify - mouse scrolling works fine, the issue is in touchpad scrolling only

**Comment by MrC0rrupted** [comment]
added https://github.com/MrC0rrupted/WinLaunch/commit/6bb5d802ec85ef548dbaf365b77af2cfbc3e4139

**Comment by kaimyel** [comment]
if i have three pages of icons, using my touchpad side scroll gesture takes it to the third (last) page and skips the second page. Same in going back from last to first.
